force-app/main/default/objects/HTTPCalloutFrameworkConfig__mdt/HTTPCalloutFrameworkConfig__mdt.object-meta.xml
<CustomObject>
    <label>HTTPCalloutFrameworkConfig</label>
    <pluralLabel>HTTPCalloutFrameworkConfig</pluralLabel>
</CustomObject>

force-app/main/default/objects/HTTPCalloutFrameworkConfig__mdt/fields/Cache_Retention_in_Seconds__c.field-meta.xml
<CustomField>
    <fullName>Cache_Retention_in_Seconds__c</fullName>
    <label>Cache Retention in Seconds</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HTTPCalloutFrameworkConfig__mdt/fields/Client_Certificate_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Certificate_Name__c</fullName>
    <label>Client Certificate Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HTTPCalloutFrameworkConfig__mdt/fields/Client_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Id__c</fullName>
    <inlineHelpText>Required if Named Credentials are not used; Recommendation is to use Named Credentials as User Name and Passwords will be exposed here.</inlineHelpText>
    <label>Client Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HTTPCalloutFrameworkConfig__mdt/fields/Consumer_Secret__c.field-meta.xml
<CustomField>
    <fullName>Consumer_Secret__c</fullName>
    <inlineHelpText>Required if Named Credentials are not used; Recommendation is to use Named Credentials as User Name and Passwords will be exposed here.</inlineHelpText>
    <label>Consumer Secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HTTPCalloutFrameworkConfig__mdt/fields/Enable_Caching__c.field-meta.xml
<CustomField>
    <fullName>Enable_Caching__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If the request is same across application, then response will be pulled from cache instead of making the actual callout</inlineHelpText>
    <label>Enable Caching</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HTTPCalloutFrameworkConfig__mdt/fields/Endpoint_URL__c.field-meta.xml
<CustomField>
    <fullName>Endpoint_URL__c</fullName>
    <label>Endpoint URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HTTPCalloutFrameworkConfig__mdt/fields/HTTP_Method__c.field-meta.xml
<CustomField>
    <fullName>HTTP_Method__c</fullName>
    <label>HTTP Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>POST</fullName>
                <default>true</default>
                <label>POST</label>
            </value>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HTTPCalloutFrameworkConfig__mdt/fields/Mock_Response_Class__c.field-meta.xml
<CustomField>
    <fullName>Mock_Response_Class__c</fullName>
    <inlineHelpText>If Mock Class mentioned, http call will not be made. Ensure the mock call implements HTTPCalloutStub</inlineHelpText>
    <label>Mock Response Class</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HTTPCalloutFrameworkConfig__mdt/fields/Named_Credentials_Name__c.field-meta.xml
<CustomField>
    <fullName>Named_Credentials_Name__c</fullName>
    <label>Named Credentials Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HTTPCalloutFrameworkConfig__mdt/fields/Org_or_Session_Partition__c.field-meta.xml
<CustomField>
    <fullName>Org_or_Session_Partition__c</fullName>
    <defaultValue>&quot;Org&quot;</defaultValue>
    <inlineHelpText>Select if this Cache is in Org or SessionPartition</inlineHelpText>
    <label>Org or Session Partition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Org</fullName>
                <default>true</default>
                <label>Org</label>
            </value>
            <value>
                <fullName>Session</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HTTPCalloutFrameworkConfig__mdt/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HTTPCalloutFrameworkConfig__mdt/fields/Platform_Cache_Partition_Name__c.field-meta.xml
<CustomField>
    <fullName>Platform_Cache_Partition_Name__c</fullName>
    <inlineHelpText>Name of the Cache Partition</inlineHelpText>
    <label>Platform Cache Partition Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HTTPCalloutFrameworkConfig__mdt/fields/Refresh_Token__c.field-meta.xml
<CustomField>
    <fullName>Refresh_Token__c</fullName>
    <inlineHelpText>If User Name &amp; Password are not given, enter Refresh_Token when not using Named Credentials. Recommendation is to use Named Credentials.</inlineHelpText>
    <label>Refresh Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HTTPCalloutFrameworkConfig__mdt/fields/Static_Headers__c.field-meta.xml
<CustomField>
    <fullName>Static_Headers__c</fullName>
    <description>Multiline, separated by : and  For e.g.
Content-Type:application/x-www-form-urlencoded
X-Resource:GetPDIRating</description>
    <inlineHelpText>Multiline, separated by : and  For e.g.
Content-Type:application/x-www-form-urlencoded
X-Resource:GetPDIRating</inlineHelpText>
    <label>Static Headers</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/HTTPCalloutFrameworkConfig__mdt/fields/Supported_Environments__c.field-meta.xml
<CustomField>
    <fullName>Supported_Environments__c</fullName>
    <label>Supported Environments</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HTTPCalloutFrameworkConfig__mdt/fields/Time_Out_in_milliseconds__c.field-meta.xml
<CustomField>
    <fullName>Time_Out_in_milliseconds__c</fullName>
    <label>Time Out (in milliseconds)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HTTPCalloutFrameworkConfig__mdt/fields/User_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Name__c</fullName>
    <label>User Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HTTPCalloutService.cls
// Add Description Here 
public with sharing class HTTPCalloutService {
    private String serviceLabel;
    private String environmentType;
    private Map<String, String> httpHeaders;
    private String namedCredential;
    private String endPointUrl;
    private String httpMethod;
    private String mockResponseClass;
    private Decimal timeOut;
    private String clientId;
    private String consumerSecret;
    private String refreshToken;
    private String userId;
    private String password;
    private String clientCertificate;
    private String requestBody;
    private List<Integer> validStatusCodes;
    private Boolean cacheEnabled;
    private Integer cacheRetentionPeriod;
    private String orgOrSession;
    private String cachePartition;
    private Cache.OrgPartition orgPart;
    private Cache.SessionPartition sessionPart;


    public HTTPCalloutService(String serviceLabel,
                              Map<String, String> dynamicHTTPHeaders,
                              String serviceParameter,
                              String requestBody) {
        List<Integer> s = new List<Integer>();
        s.add(200);
        initObject( serviceLabel,
                    dynamicHTTPHeaders,
                    serviceParameter,
                    requestBody, 
                    s);
    }

    public HTTPCalloutService(String serviceLabel,
                              Map<String, String> dynamicHTTPHeaders,
                              String serviceParameter,
                              String requestBody,
                              List<Integer> validStatusCodes) {
        initObject( serviceLabel,
                    dynamicHTTPHeaders,
                    serviceParameter,
                    requestBody, 
                    validStatusCodes);
    }

    private void initObject(String serviceLabel,
                            Map<String, String> dynamicHTTPHeaders,
                            String serviceParameter,
                            String requestBody,
                            List<Integer> validStatusCodes) {
        this.serviceLabel = serviceLabel;
        String myDomainUrl = System.Url.getOrgDomainUrl().toExternalForm();
        if (myDomainUrl.indexOf('--') > 0) {
            this.environmentType = myDomainUrl.substringAfter('--').substringBefore('.');
        }
        else {
            this.environmentType = 'prod';
        }

        System.debug('Environment: ' + this.environmentType);

        this.validStatusCodes = validStatusCodes.clone();

        List<HTTPCalloutFrameworkConfig__mdt> h = new List<HTTPCalloutFrameworkConfig__mdt>();
        String configSOQL = 'SELECT  Client_Certificate_Name__c, ' +
                    '        Client_Id__c, ' +
                    '        Consumer_Secret__c,'  +
                    '        Endpoint_URL__c, ' +
                    '        HTTP_Method__c, ' +
                    '        Mock_Response_Class__c, ' +
                    '        Named_Credentials_Name__c, ' +
                    '        Refresh_Token__c, ' +
                    '        Static_Headers__c, ' +
                    '        Time_Out_in_milliseconds__c, ' +
                    '        User_Name__c, ' +
                    '        Password__c, ' +
                    '        Enable_Caching__c, ' +
                    '        Cache_Retention_in_Seconds__c, ' +
                    '        Org_or_Session_Partition__c, ' +
                    '        Platform_Cache_Partition_Name__c ' +
                    'FROM    HTTPCalloutFrameworkConfig__mdt ' +
                    'WHERE   MasterLabel = :serviceLabel ';

        try {
            /* Production needs to have a separate unique configuration and can't be combined with
            ** sandbox configuration to ensure there is clear distinction.
            */
            if (this.environmentType == 'prod') {
                h = Database.query(configSOQL +
                                    'AND Supported_Environments__c = \'' + this.environmentType + '\'');
            }
            else {
                h = Database.query(configSOQL +
                    'AND     (Supported_Environments__c LIKE \'%,' + this.environmentType + ',%\' OR ' + 
                    '         Supported_Environments__c LIKE \'' + this.environmentType + ',%\' OR ' + 
                    '         Supported_Environments__c LIKE \'%,' + this.environmentType + '\' OR ' + 
                    '         Supported_Environments__c LIKE \'' + this.environmentType + '\')');
            }
        }
        catch(Exception ex) {
            throw new HTTPCalloutService.ServiceException('Error! Service Label: ' + serviceLabel + ' & Environment Type: ' + environmentType + '\n' + ex.getMessage());
        }
        if (h.size() > 1) {
            throw new HTTPCalloutService.ServiceException('Error! Multiple configurations found for Service Label: ' + serviceLabel + ' & Environment Type: ' + environmentType );
        }

        if (h.size() == 1) System.debug('Found a real config');

        if (h.size() == 0) {
            if (this.environmentType == 'prod') {
                throw new HTTPCalloutService.ServiceException('Error! No configuration found for Service Label: ' + serviceLabel + ' & Environment Type: ' + environmentType );
            }
            try {
                h = Database.query(configSOQL +
                    'AND     (Supported_Environments__c LIKE \'%,mock,%\' OR ' + 
                    '         Supported_Environments__c LIKE \'mock,%\' OR ' + 
                    '         Supported_Environments__c LIKE \'%,mock\' OR ' + 
                    '         Supported_Environments__c LIKE \'mock\' OR ' +
                    '         Supported_Environments__c LIKE \'%,default,%\' OR ' + 
                    '         Supported_Environments__c LIKE \'default,%\' OR ' + 
                    '         Supported_Environments__c LIKE \'%,default\' OR ' + 
                    '         Supported_Environments__c LIKE \'default\')' 
                    );

            }
            catch(Exception ex) {
                throw new HTTPCalloutService.ServiceException('Error! Service Label: ' + serviceLabel + ' & Environment Type: ' + environmentType + '\n' + ex.getMessage());
            }
            if (h.size() > 1) {
                throw new HTTPCalloutService.ServiceException('Error! Multiple mock/default configurations found for Service Label: ' + serviceLabel + ' & Environment Type: ' + environmentType );
            }
            if (h.size() == 0) {
                throw new HTTPCalloutService.ServiceException('Error! No real or mock configuration found for Service Label: ' + serviceLabel + ' & Environment Type: ' + environmentType );
            }
            if (h.size() == 1) System.debug('Found a mock config');
        }
        
        System.debug(h);
        this.namedCredential = h[0].Named_Credentials_Name__c;
        this.endPointUrl = h[0].Endpoint_URL__c + serviceParameter;

        if (namedCredential != null) {
            this.endPointUrl = 'callout:' + namedCredential + serviceParameter;
        }

        this.httpMethod = h[0].HTTP_Method__c;
        this.mockResponseClass = h[0].Mock_Response_Class__c;
        this.timeOut = h[0].Time_Out_in_milliseconds__c;
        this.clientId = h[0].Client_Id__c;
        this.consumerSecret = h[0].Consumer_Secret__c;
        this.refreshToken = h[0].Refresh_Token__c;
        this.userId = h[0].User_Name__c;
        this.password = h[0].Password__c;
        this.clientCertificate = h[0].Client_Certificate_Name__c;
        this.cacheEnabled = h[0].Enable_Caching__c;
        this.cacheRetentionPeriod = (h[0].Cache_Retention_in_Seconds__c == null ? 0 : h[0].Cache_Retention_in_Seconds__c.intValue());
        this.orgOrSession = h[0].Org_or_Session_Partition__c;
        this.cachePartition = h[0].Platform_Cache_Partition_Name__c;

        List<String> keyValue;
        this.httpHeaders = new Map<String,String>();
        if (h[0].Static_Headers__c != null) {
            for (String sh : h[0].Static_Headers__c.split('\n')) {
                keyValue = sh.split(':');
                if (keyValue.size() != 2) {
                    throw new HTTPCalloutService.ServiceException('Error! Bad Static Header found in Service Label: ' + serviceLabel + ' & Environment Type: ' + environmentType + '\n' + keyValue);
                }
                this.httpHeaders.put(keyValue[0], keyValue[1]);
            }
        }
        if (dynamicHTTPHeaders != null) {
            this.httpHeaders.putAll(dynamicHTTPHeaders);
        }
        System.debug('HttpHeaders: ' + this.httpHeaders);

        this.requestBody = requestBody;

        if (this.cacheEnabled) {
            if (this.orgOrSession == 'Org') 
                this.orgPart = Cache.Org.getPartition(this.cachePartition);
            else
                this.sessionPart = Cache.Session.getPartition(this.cachePartition);
        }

    }

    public HTTPCalloutResponse callOut() {
        if (mockResponseClass != null) {
            Type t = Type.forName(mockResponseClass);
            HTTPCalloutStub v = (HTTPCalloutStub)t.newInstance();
            return v.getResponse();
        }

        String keyToHash = '';
        try {
            HttpRequest req = new HttpRequest();
            req.setEndpoint(this.endPointUrl);
            req.setMethod(this.httpMethod);

            for (String key : this.httpHeaders.keySet()){
                req.setHeader(key, this.httpHeaders.get(key));
            }
            req.setBody(requestBody);

            if (this.timeOut != null) req.setTimeout(this.timeOut.intValue());

            Blob targetBlob;
            String hash;
            if (this.cacheEnabled && this.cacheRetentionPeriod > 0) {
                keyToHash = this.endPointUrl + this.httpMethod;
                for (String key : this.httpHeaders.keySet()){
                    keyToHash += key + this.httpHeaders.get(key);
                }
                keyToHash += this.requestBody;

                targetBlob = Blob.valueOf(keyToHash);
                hash = EncodingUtil.convertToHex(Crypto.generateDigest('MD5', targetBlob));

                System.Debug('keyToHash Length:' + keyToHash.length() + ' keyToHash: ' + keyToHash);
                System.Debug('Hash Length:' + hash.length() + ' hash: ' + hash);

                if (this.orgOrSession == 'Org' ? orgPart.contains(hash) : sessionPart.contains(hash)) {
                    HTTPCalloutResponse cachedResponse = (HTTPCalloutResponse) (orgOrSession == 'Org' ? orgPart.get(hash) : sessionPart.get(hash));
                    if (cachedResponse != null) {
                        System.Debug('Getting from Cache');
                        return cachedResponse;
                    }
                }
            }

            Http httpClient = new Http();
            HttpResponse rsp = httpClient.send(req);
            
            if (!this.validStatusCodes.contains(rsp.getStatusCode())) {
                throw new HTTPCalloutService.ServiceException('Error! Service Label: ' + serviceLabel + ' & Environment Type: ' + environmentType + '\n' + 
                                                                'Status: ' + rsp.getStatusCode() + '-' + rsp.getStatus());
            }

            HTTPCalloutResponse response = new HTTPCalloutResponse (rsp.getStatusCode(), rsp.getStatus(), rsp.getBody());

            if (this.cacheEnabled) {
                if (this.cacheRetentionPeriod > 0) {
                    if (this.orgOrSession == 'Org')  {
                        orgPart.put(hash, response, this.cacheRetentionPeriod);
                    }
                    else {
                        sessionPart.put(hash, response, this.cacheRetentionPeriod);
                    }
                }
                else {
                    if (this.orgOrSession == 'Org')  {
                        orgPart.put(hash, response);
                    }
                    else {
                        sessionPart.put(hash, response);
                    }
                }
            }
            return (response);
        }
        catch(Exception ex) {
            throw new HTTPCalloutService.ServiceException(ex.getMessage() + '\nStack Trace: ' + ex.getStackTraceString());
        } 
    }

    public class ServiceException extends Exception { }
}